# Generated by Django 5.2.4 on 2025-07-09 05:12

import ckeditor.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_alter_categoria_options_alter_menuitem_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoria',
            options={'verbose_name': 'Categoría', 'verbose_name_plural': 'Categorías'},
        ),
        migrations.AlterModelOptions(
            name='menuitem',
            options={'ordering': ['order'], 'verbose_name': 'Elemento de Menú', 'verbose_name_plural': 'Elementos de Menú'},
        ),
        migrations.AlterModelOptions(
            name='producto',
            options={'ordering': ['-fecha_creacion'], 'verbose_name': 'Producto', 'verbose_name_plural': 'Productos'},
        ),
        migrations.AlterModelOptions(
            name='sitesetting',
            options={'verbose_name': 'Configuración del Sitio', 'verbose_name_plural': 'Configuraciones del Sitio'},
        ),
        migrations.AlterModelOptions(
            name='subcategoria',
            options={'verbose_name': 'Subcategoría', 'verbose_name_plural': 'Subcategorías'},
        ),
        migrations.AlterModelOptions(
            name='variacion',
            options={'verbose_name': 'Variación', 'verbose_name_plural': 'Variaciones'},
        ),
        migrations.RenameField(
            model_name='producto',
            old_name='created_at',
            new_name='fecha_creacion',
        ),
        migrations.RenameField(
            model_name='producto',
            old_name='updated_at',
            new_name='ultima_actualizacion',
        ),
        migrations.AddField(
            model_name='producto',
            name='long_description',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Descripción Larga (con formato)'),
        ),
        migrations.AddField(
            model_name='producto',
            name='stock',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='order',
            field=models.IntegerField(default=0, help_text='Orden de aparición en el menú'),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='url',
            field=models.CharField(help_text='URL a la que apunta el elemento de menú', max_length=255),
        ),
        migrations.AlterField(
            model_name='producto',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='descuento',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Porcentaje de descuento (ej. 0.10 para 10%)', max_digits=5),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='key',
            field=models.CharField(help_text="Clave de la configuración (ej. 'whatsapp_number')", max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='value',
            field=models.CharField(help_text='Valor de la configuración', max_length=255),
        ),
        migrations.AlterField(
            model_name='subcategoria',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='subcategoria',
            unique_together={('categoria', 'nombre')},
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='productos/galeria/')),
                ('alt_text', models.CharField(blank=True, help_text='Texto alternativo para la imagen (SEO y accesibilidad)', max_length=255)),
                ('order', models.IntegerField(default=0, help_text='Orden de visualización de la imagen')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='store.producto')),
            ],
            options={
                'verbose_name': 'Imagen de Producto',
                'verbose_name_plural': 'Imágenes de Productos',
                'ordering': ['order'],
            },
        ),
    ]
