# Generated by Django 5.2.4 on 2025-07-09 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0004_alter_categoria_options_alter_menuitem_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Anuncio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=200)),
                ("descripcion", models.TextField(blank=True, null=True)),
                ("imagen", models.ImageField(upload_to="anuncios/")),
                (
                    "url",
                    models.URLField(
                        blank=True,
                        help_text="URL a la que redirige el anuncio (opcional)",
                        null=True,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="¿Está activo este anuncio?"
                    ),
                ),
                (
                    "order",
                    models.IntegerField(
                        default=0, help_text="Orden de visualización en el carrusel"
                    ),
                ),
                ("fecha_creacion", models.DateTimeField(auto_now_add=True)),
                ("ultima_actualizacion", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Anuncio",
                "verbose_name_plural": "Anuncios",
                "ordering": ["order", "-fecha_creacion"],
            },
        ),
    ]
