# Generated by Django 5.2.4 on 2025-07-10 06:22

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0005_anuncio"),
    ]

    operations = [
        migrations.AlterField(
            model_name="anuncio",
            name="imagen",
            field=cloudinary.models.CloudinaryField(
                blank=True, max_length=255, null=True, verbose_name="imagen"
            ),
        ),
        migrations.AlterField(
            model_name="productimage",
            name="alt_text",
            field=models.CharField(
                blank=True, help_text="Texto alternativo para la imagen", max_length=255
            ),
        ),
        migrations.AlterField(
            model_name="productimage",
            name="image",
            field=cloudinary.models.CloudinaryField(
                blank=True, max_length=255, null=True, verbose_name="imagen"
            ),
        ),
        migrations.AlterField(
            model_name="producto",
            name="imagen",
            field=cloudinary.models.CloudinaryField(
                blank=True, max_length=255, null=True, verbose_name="imagen"
            ),
        ),
    ]
