# Generated by Django 5.2.4 on 2025-07-11 05:26

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0006_alter_anuncio_imagen_alter_productimage_alt_text_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="variacion",
            name="color_hex",
            field=models.CharField(
                blank=True,
                help_text="Código HEX del color (ej. #FF0000)",
                max_length=7,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="variacion",
            name="imagen",
            field=cloudinary.models.CloudinaryField(
                blank=True,
                help_text="Imagen específica para esta variación",
                max_length=255,
                null=True,
                verbose_name="imagen_variacion",
            ),
        ),
        migrations.AddField(
            model_name="variacion",
            name="price_override",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Opcional: Precio para esta variación. Si está vacío, usa el precio del producto principal.",
                max_digits=10,
                null=True,
            ),
        ),
    ]
