# Generated by Django 5.2.4 on 2025-07-12 19:10

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_alter_variacion_tono'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='imagen_circular',
            field=cloudinary.models.CloudinaryField(blank=True, help_text='Imagen circular para la categoría (ej. para la página de inicio)', max_length=255, null=True, verbose_name='imagen_circular'),
        ),
        migrations.AlterField(
            model_name='variacion',
            name='tono',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
