# Generated by Django 5.2.4 on 2025-07-14 21:15

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_favorito'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='precio',
            field=models.DecimalField(decimal_places=0, default=Decimal('0'), help_text='Ingrese el precio sin puntos ni comas (ej. 30000 para $30.000)', max_digits=10),
        ),
    ]
