services:
  - type: web
    name: lumiere-glamour-web
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn lumiere_glamour.wsgi:application
    envVars:
      - key: DEBUG
        value: False
      - key: SECRET_KEY
        generateValue: true
      - key: ALLOWED_HOSTS
        value: lumiere-glamour.onrender.com
